# Generated by Django 2.1.2 on 2019-06-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_patient_cabin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='nurse_name',
        ),
    ]
