# Generated by Django 2.1.2 on 2019-06-27 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_cabin_nurse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='nurse_name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Nurse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='cabin_name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Cabin'),
            preserve_default=False,
        ),
    ]
