# Generated by Django 2.1.2 on 2019-06-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20190627_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='nurse_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cabin_name',
        ),
    ]
